import { FormEvent, useEffect, useState } from 'react'
import { AgentRun, AiLead, api } from '../../shared/api/client'
import { LeadRanker } from './LeadRanker'
import { TelemetryPanel, TelemetryResult } from './TelemetryPanel'
import { ProductionResult } from './ProductionResult'
import './AiDesk.css'
import './LeadInbox.css'
import './DraftAction.css'
import './AiDeskPanels.css'

export function AiDesk() {
  const [runs, setRuns] = useState<AgentRun[]>([]), [leads, setLeads] = useState<AiLead[]>([]), [headline, setHeadline] = useState(''), [topic, setTopic] = useState('general'), [context, setContext] = useState(''), [notice, setNotice] = useState('')
  const load = () => { void Promise.all([api.agentRuns(), api.aiLeads()]).then(([history, inbox]) => { setRuns(history.items); setLeads(inbox) }).catch(error => setNotice(error.message)) }
  useEffect(load, [])
  const generate = async (event: FormEvent) => { event.preventDefault(); try { setNotice('Generating an editorial draft…'); const run = await api.produceDraft({ headline, topic, context }); setRuns(items => [run, ...items]); setNotice('Draft generated. Review the provenance before using it in a story.') } catch (error) { setNotice(error instanceof Error ? error.message : 'Generation failed.') } }
  const createDraft = async (run: AgentRun) => { const output = run.output as { title?: string; dek?: string; content_html?: string; content_json?: Record<string, unknown>; provenance?: string[] }; if (!output.title || !output.content_html) return; try { await api.createArticle({ title: output.title, dek: output.dek ?? '', content_html: output.content_html, content_json: output.content_json ?? {}, topic, tags: ['ai-assisted', ...(output.provenance ?? [])] }); setNotice('Editable draft created in Stories. It remains unpublished until human review and approval.') } catch (error) { setNotice(error instanceof Error ? error.message : 'Unable to create draft.') } }
  const decide = async (lead: AiLead, decision: 'approve' | 'reject') => { try { await api.decideLead(lead.id, decision); setNotice(`Lead ${decision}d.`); load() } catch (error) { setNotice(error instanceof Error ? error.message : 'Unable to update lead.') } }
  const retry = async (run: AgentRun) => { try { const next = await api.retryAgentRun(run.id); setRuns(items => [next, ...items]); setNotice('Agent run retried with the exact recorded input.') } catch (error) { setNotice(error instanceof Error ? error.message : 'Unable to retry this run.') } }
  return <section className="ai-desk"><header><div><p className="eyebrow">PHASE 7 · AI NEWSROOM</p><h1>AI editorial desk</h1><p>Generate reviewable drafts. AI output is always an editorial suggestion, never a published story.</p></div></header><LeadRanker onRanked={load} onNotice={setNotice}/><section className="ai-leads"><header><h2>Lead inbox</h2><button onClick={load}>Refresh</button></header>{leads.length ? leads.map(lead => <article key={lead.id}><div><b>{lead.headline}</b><small>{lead.topic} · score {lead.priority_score ?? '—'}</small><p>{lead.suggested_angle || lead.reasoning || 'Awaiting selection run.'}</p></div><span>{lead.status}</span>{lead.status === 'pending' && <footer><button onClick={() => void decide(lead, 'reject')}>Reject</button><button className="lead-approve" onClick={() => { setHeadline(lead.headline); setTopic(lead.topic); setContext(lead.reasoning || lead.suggested_angle || ''); void decide(lead, 'approve') }}>Approve & draft</button></footer>}</article>) : <p className="ai-empty">Run Selection Agent with approved intake leads to populate this inbox.</p>}</section><div className="ai-desk-grid"><form className="ai-compose" onSubmit={generate}><h2>Production workspace</h2><label>Headline<input value={headline} onChange={event => setHeadline(event.target.value)} minLength={5} required/></label><label>Topic<input value={topic} onChange={event => setTopic(event.target.value)} required/></label><label>Verified source context<textarea value={context} onChange={event => setContext(event.target.value)} placeholder="Paste verified notes, quotes, or source context…"/></label><button>Generate grounded draft</button><small>{notice}</small></form><section className="ai-runs"><header><h2>Agent run history</h2><button onClick={load}>Refresh</button></header>{runs.length ? runs.map(run => <article key={run.id}><div><b>{run.agent}</b><span className={run.status}>{run.status}</span></div><p>{run.model} · {run.prompt_version} · {run.duration_ms}ms</p><ProductionResult run={run}/><TelemetryResult run={run}/>{run.agent === 'production' && run.status === 'succeeded' && <button className="create-ai-draft" onClick={() => void createDraft(run)}>Create editable draft</button>}{run.error ? <><small className="run-error">{run.error}</small><button className="create-ai-draft" onClick={() => void retry(run)}>Retry run</button></> : <details><summary>Source context & output</summary><pre>{JSON.stringify({ input: run.input, output: run.output }, null, 2)}</pre></details>}</article>) : <p className="ai-empty">No agent runs yet.</p>}</section></div><TelemetryPanel onRun={run => setRuns(items => [run, ...items])} onNotice={setNotice}/></section>
}
